version: '3.4'

services:
  movieadminv3:
    image: movieadminv3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8000:80
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
